### ISSUE TITLE
使用的时候报错  

### ISSUE THREAD

**Issue by Aklnegale** [slippersheepig/chatgpt-web#1]
执行docker-compose up之后展示 standard_init_linux.go:228: exec user process caused: exec format error

**Comment by chldong** [comment]
https://blog.csdn.net/chrispaul610/article/details/121955817

**Comment by yuexiadudiao** [comment]
内置端口的问题，把容器内的80端口换成其它的就可以起来了

**Comment by slippersheepig** [comment]
> 执行docker-compose up之后展示 standard_init_linux.go:228: exec user process caused: exec format error

应该是架构不兼容，请自行使用dockerfile构建镜像
