### ISSUE TITLE
老哥请教下怎么启动对话？

### ISSUE THREAD

**Issue by yw2278** [slippersheepig/chatgpt-web#10]
我已经用docker-compose up -d拉起了镜像，docker-compose.yml配置的ports是 "8888:8088" ，但是用http://8888:8088/chat进不去，想问下怎么启动，多谢了

**Comment by slippersheepig** [comment]
把8888改成你机器的IP

**Comment by yw2278** [comment]
多谢能启动了，但是有新的问题
![image](https://user-images.githubusercontent.com/22030956/222620457-09331954-06db-4ab5-8aa9-d70c66d8f96a.png)
一直卡在反应这边

**Comment by yw2278** [comment]
可以了，多谢
