### ISSUE TITLE
服务器500

### ISSUE THREAD

**Issue by Whitehorse-rainbow** [slippersheepig/chatgpt-web#12]
配置正确，api和梯子正常，本地搭建500，有遇到这种情况吗

**Comment by slippersheepig** [comment]
[duplicated](https://github.com/slippersheepig/chatgpt-html/issues/21)

**Comment by Whitehorse-rainbow** [comment]
我已经解决了，我用的v2ray，然后他自己会开放socks代理端口，我就用socks.set_default_proxy(socks.SOCKS5, '127.0.0.1', 10808)
socket.socket = socks.socksocket解决了翻墙的问题，也不用买服务器啥的了
