### ISSUE TITLE
`api.openai.com`is blocked in China

### ISSUE THREAD

**Issue by dreamrfy** [slippersheepig/chatgpt-web#13]
首先除api部分其他部分都没有修改，部署完成之后能正常打开，但是对话就会出现这个问题
请求出错，,Post
"https://api.open a i.com/v1/cha
t/completions:proxy connect
tcp:dial tcp:lookup
host.docker.internal on
8.8.8.8:53:no such host

我通过其他应用程序测试并不是我open api错误，现在不知道什么情况，请大佬帮忙看看

**Comment by slippersheepig** [comment]
据说大陆现在访问不了api.openai.com了，应该是这个原因导致的

**Comment by slippersheepig** [comment]
1.

**Comment by dreamrfy** [comment]
> 据说大陆现在访问不了 api.openai.com 了，应该是这个原因导致的

这样啊，谢谢，我后面持续关注一下
