### ISSUE TITLE
出现404错误

### ISSUE THREAD

**Issue by wudingjian** [slippersheepig/chatgpt-web#14]
一、提示：Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

二、日志如下：

[2023-03-07 16:09:21 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2023-03-07 16:09:21 +0000] [1] [INFO] Listening at: http://0.0.0.0:8088 (1)
[2023-03-07 16:09:21 +0000] [1] [INFO] Using worker: gevent
[2023-03-07 16:09:21 +0000] [8] [INFO] Booting worker with pid: 8

三、docker-compose.yml 没问题配置如下：（docker容器启动正常的）

services:
  chatgpt:
    image: sheepgreen/chatgpt-web #如果是arm架构，需要改成chatgpt-web:arm
    container_name: webchat
    volumes:
      - ./.env:/chatgpt-web/.env
    restart: always
    networks:  #网络设置
        app_net:
          ipv4_address: 172.18.0.16
networks:
     app_net:
        external: true

没有端口，是内部有npm反代的

四、配置文件.env
OPENAI_API_KEY= "sk-*************************************************"

**Comment by slippersheepig** [comment]
404是没找到对应url，往这个方向检查吧
项目本身的访问地址是http://ip:port/chat
也可以检查其他地方是不是有路径没对上

**Comment by wudingjian** [comment]
感谢回复

http://ip:port/chat   是可以访问了聊天界面了，但发送聊天内容时，窗口中还是出现：
Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
这个应该怎么检查？

**Comment by slippersheepig** [comment]
https://github.com/slippersheepig/chatgpt-web/blob/f2644c3c19488a07944a2ab115ceb77f2aafea41/main.py#L22
https://github.com/slippersheepig/chatgpt-web/blob/f2644c3c19488a07944a2ab115ceb77f2aafea41/main.py#L28
https://github.com/slippersheepig/chatgpt-web/blob/f2644c3c19488a07944a2ab115ceb77f2aafea41/static/script.js#L28
类似的这些地方都要看

**Comment by slippersheepig** [comment]
since there's no response for a while, close now
