### ISSUE TITLE
OpenAI API - Access Terminated

### ISSUE THREAD

**Issue by MZ44** [slippersheepig/chatgpt-web#16]
收到openai的邮件，我的api被封了 - -！

<img width="567" alt="image" src="https://user-images.githubusercontent.com/38270274/223952142-2493dde8-0d2d-4322-83a1-0f925bfc7e7f.png">

**Comment by slippersheepig** [comment]
`因为向OPENAI提问的内容频繁触及敏感词而导致的封号`
很早之前，注册账号还是送30刀免费限额的时候，我的API KEY就被别人冲到封了，在后台看日志发现他一直想调教AI说出非法内容
后来OPENAI升级了一版，不允许调教了，然后我的几个KEY都安全用到没额度
最近可能又有人有歪点子吧，OPENAI又开始封号了，没办法，既然公开给别人使用就得承担风险
