### ISSUE TITLE
这是什么问题

### ISSUE THREAD

**Issue by ZREternal** [slippersheepig/chatgpt-web#17]
webchat    | [2023-03-09 11:40:45 +0000] [6] [INFO] Worker exiting (pid: 6)
webchat    | [2023-03-09 11:40:45 +0000] [1] [INFO] Shutting down: Master
webchat    | [2023-03-09 11:40:45 +0000] [1] [INFO] Reason: Worker failed to boot.
webchat    | [2023-03-09 11:40:46 +0000] [1] [INFO] Starting gunicorn 20.1.0
webchat    | [2023-03-09 11:40:46 +0000] [1] [INFO] Listening at: http://0.0.0.0:8088 (1)
webchat    | [2023-03-09 11:40:46 +0000] [1] [INFO] Using worker: gevent
webchat    | [2023-03-09 11:40:46 +0000] [6] [INFO] Booting worker with pid: 6
webchat    | [2023-03-09 11:40:46 +0000] [6] [ERROR] Exception in worker process

容器一直反复重启
version: "3.3"
services:
  chatgpt:
    image: sheepgreen/chatgpt-web #如果是arm架构，需要改成chatgpt-web:arm
    container_name: webchat
    volumes:
      - ./.env:/chatgpt-web/.env
    ports:
      - "8888:8088" #8088为容器内部端口，不可更改；8888为外部映射端口，可自行更改
    restart: always

**Comment by Tianchen627** [comment]
插眼，我也遇到了这个问题

**Comment by slippersheepig** [comment]
closed for stale
