### ISSUE TITLE
manifest for docker.io/sheepgreen/chatgpt-web:latest not found

### ISSUE THREAD

**Issue by byYufeng** [slippersheepig/chatgpt-web#20]
还以为是我docker版本的原因 结果pull都pull不下来

**Comment by slippersheepig** [comment]
> 还以为是我docker版本的原因 结果pull都pull不下来

`manifest not found`我的镜像只有`amd64`和`arm64`架构，其他架构需自行使用Dockerfile编译`docker build`
注意：因为openai所需的tiktoken依赖只有上述两种架构的wheels，其他架构需具备rust编译环境，请自行解决

**Comment by byYufeng** [comment]
docker build已解决 感谢～
