### ISSUE TITLE
AttributeError: 'Chatbot' object has no attribute 'reset'

### ISSUE THREAD

**Issue by linqingping** [slippersheepig/chatgpt-web#21]
![image](https://user-images.githubusercontent.com/20528139/231979458-418b83c3-8135-4d1d-ab5b-e9eac4c48f68.png)

**Comment by slippersheepig** [comment]
According to [python version ](https://github.com/acheong08/ChatGPT#suport-python-version) , you should update your python, it's not support python 3.7

**Comment by linqingping** [comment]
> According to [python version ](https://github.com/acheong08/ChatGPT#suport-python-version) , you should update your python, it's not support python 3.7
Thanks for the reply,what version should i use?

**Comment by slippersheepig** [comment]
> > According to [python version ](https://github.com/acheong08/ChatGPT#suport-python-version) , you should update your python, it's not support python 3.7
> > Thanks for the reply,what version should i use?

at least 3.9, 3.11 and above is recommended.

**Comment by linqingping** [comment]
> > > According to [python version ](https://github.com/acheong08/ChatGPT#suport-python-version) , you should update your python, it's not support python 3.7
> > > Thanks for the reply,what version should i use?
> 
> at least 3.9, 3.11 and above is recommended.

ok,Thanks!
