### ISSUE TITLE
修改chat.html 不起作用。

### ISSUE THREAD

**Issue by yoursunboy** [slippersheepig/chatgpt-web#4]
docker-compose.yml 中的chat.html 路径也修改了 。我的 pwd 是 ：/root/gpt/chat.html 

chat.html 的内容也编辑了，
docker 也 restart webchat 了。

可是不生效~

**Comment by slippersheepig** [comment]
因为dockerfile创建了非root用户，不支持root路径。换路径，或者把dockerfile里的创建用户那几行删掉再构建
