### ISSUE TITLE
Unsupported config option for services: 'chatgpt'

### ISSUE THREAD

**Issue by Kot-3** [slippersheepig/chatgpt-web#5]
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services: 'chatgpt'

**Comment by slippersheepig** [comment]
docker-compose.yml最上面加一行`version: '3'`或者`version: '2'`（根据你安装的docker compose版本会有不同）

**Comment by Kot-3** [comment]
> docker-compose.yml最上面加一行`version: '3'`或者`version: '2'`（根据你安装的docker compose版本会有不同）
可以了完美解决 非常感谢解答
