### ISSUE TITLE
docker-compose.yml 替换自用网页chat.html无效

### ISSUE THREAD

**Issue by GalaxyHoldYY** [slippersheepig/chatgpt-web#8]
无法替换自用的网页，例如下面的代码 volumes挂载路径设置以后，重启docker-compose，chat.html还是作者的UI界面，请问应该如何修改？
  volumes:
    - ./chat.html:/chatgpt-web/templates/chat.html #默认内置我的UI，如需替换自用网页请取消注释

**Comment by slippersheepig** [comment]
docker restart webchat，另外可以用无痕模式再打开查看，有可能是浏览器缓存

**Comment by GalaxyHoldYY** [comment]
> docker restart webchat，另外可以用无痕模式重新打开查看，有可能是浏览器存档

使用无痕模式，命令 docker restart webchat，还是无法替换chat.html，配置文件，需要注意哪些？

**Comment by slippersheepig** [comment]
> > docker restart webchat，另外可以用无痕模式重新打开查看，有可能是浏览器存档
> 
> 使用无痕模式，命令 docker restart webchat，还是无法替换chat.html，配置文件，需要注意哪些？

`chat.html`需要和`docker-compose.yml`在同一目录下

**Comment by slippersheepig** [comment]
since there's no response for a while, close now

**Comment by Yudezhi** [comment]
same issue.
